name: AI Governance Gap Snapshot
on: [push, pull_request]
jobs:
  gap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install pyyaml tabulate
      - name: Run gap snapshot
        run: |
          python scripts/run_gap_assessment.py \
            --docs docs \
            --checklist ai/checklists/42001_checklist.yaml \
            --out out/42001-gap.md
      - uses: actions/upload-artifact@v4
        with:
          name: iso42001-gap-snapshot
          path: out/42001-gap.md
