name: App & Repo Security

on:
  push:
  pull_request:

jobs:
  sast-and-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit

      - name: Bandit (SAST)
        run: bandit -r app -ll || true  # keep pipeline going for demo

      - name: Dependency audit (pip-audit)
        run: pip-audit -r app/requirements.txt || true

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: "--redact --verbose"
